CC       = gcc
CFLAGS   = -c -g -O2 -DUNIX -I./h -I..
LFLAGS   = -s -L../fidoconf -L../smapi

OBJS    = uuecode.o uuefile.o scanmsg.o dupe.o

all: $(OBJS) \
	hptucode

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $*.c

hptucode: $(OBJS)
	$(CC) $(LFLAGS) -o hptucode $(OBJS) -lsmapisun -lfidoconfigsun

clean:
	-rm -f *.o
	-rm -f *~
	-rm -f hptucode
	-rm -f core
