CC      = wcc386
LINK    = WLINK

CFLAGS  = -zq -wx -bt=nt -ih;.. -oneatx -5
LFLAGS  =

OBJS    = uuecode.obj uuefile.obj scanmsg.obj dupe.obj

all: $(OBJS) hptucode.exe

$(OBJS): *.c
  @echo compiling $*.c
  $(CC) $(CFLAGS) $*.c

hptucode.exe: $(OBJS)
  @echo linking hptucode
  $(LINK) $(LFLAGS) FILE uuecode.obj, uuefile.obj, scanmsg.obj, dupe.obj Library ..\smapi\smapiwcw, ..\fidoconf\fconfwcw.lib NAME hptucode.exe

clean:
	-DEL *.OBJ
	-DEL *.err
	-DEL hptucode.exe

