CC      = gcc
CFLAGS=-DNT -D__NT__ -DWINNT -D__CYG__ -I../h -I../.. -Wall -pedantic -c -Wno-char-subscripts
COPT=	-O2
LFLAGS=-L../../smapi/ -L../../fidoconf


OBJS    = uuecode.o uuefile.o scanmsg.o dupe.o
SRC_DIR = ../src/

all: hpucode.exe

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $<

hpucode.exe: $(OBJS)
	$(CC) $(LFLAGS) -o hpucode.exe $(OBJS) -lfidoconfigmgw -lsmapimgw -luser32

clean:
	-rm -f *.o
	-rm *~
	-rm 

distclean: clean
	-rm hpucode.exe
	-rm *.1.gz
	-rm *.log
