# $Id$
# Legacy makefile for CygWin
#

CC      = gcc
CFLAGS=-c -O3 -D__NT__ -I../h -I../.. -Wall -pedantic -mno-cygwin
LFLAGS=-mno-cygwin -L../../smapi/ -L../../fidoconf

SRC_DIR = ../src/
OBJS    = uuecode.o uuefile.o scanmsg.o dupe.o

all: $(OBJS) hpucode.exe

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $<

hpucode.exe: $(OBJS)
	$(CC) $(LFLAGS) -o hpucode.exe $(OBJS) -lfidoconfigcyg -lsmapicyg

clean:
	-rm -f *.o
	-rm *~
	-rm 

distclean: clean
	-rm hpucode.exe
	-rm *.1.gz
	-rm *.log
