CC      = gcc
CFLAGS=-DNT -D__NT__ -DWINNT -D__CYG__ -I. -I.. -Wall -pedantic -c -Wno-char-subscripts
COPT=	-O2
LFLAGS=-L../smapi/ -L../fidoconf


OBJS    = uuecode.o uuefile.o scanmsg.o dupe.o

all: $(OBJS) hpucode.exe

%.o: %.c
	$(CC) $(CFLAGS) $*.c

hpucode.exe: $(OBJS)
	$(CC) $(LFLAGS) -o hpucode.exe $(OBJS) -lfidoconfigmgw -lsmapimgw -luser32

clean:
	-rm -f *.o
	-rm *~
	-rm 
	-rm hpucode.exe

distclean: clean
	-rm hpucode.exe
	-rm *.1.gz
	-rm *.log
