# $Id$
# Legacy makefile for Sun Solaris (SunOS)
#
# Use GNU version of make (gmake)
#
CC       = gcc
CFLAGS   = -c -g -O2 -DUNIX -I../h -I../..
LFLAGS   = -s -L../../fidoconf -L../../smapi

OBJS    = uuecode.o uuefile.o scanmsg.o dupe.o
SRC_DIR = ../src/

all: $(OBJS) \
	hpucode

%.o: $(SRC_DIR)%.c
	$(CC) $(CFLAGS) $<

hpucode: $(OBJS)
	$(CC) $(LFLAGS) -o hpucode $(OBJS) -lsmapisun -lfidoconfigsun

clean:
	-rm -f *.o
	-rm -f *~
	-rm -f core

distclean: clean
	-rm -f hpucode
